
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_logo_lb = new javax.swing.JLabel();
        user_name_lb = new javax.swing.JLabel();
        user_name_tf = new javax.swing.JTextField();
        password_lb = new javax.swing.JLabel();
        password_pf = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        sign_up_btn = new javax.swing.JButton();
        correct_lb = new javax.swing.JLabel();
        admin_login_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login_logo_lb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_logo_lb.setForeground(new java.awt.Color(0, 153, 0));
        login_logo_lb.setText("USER LOGIN PAGE");

        user_name_lb.setText("User Name");

        password_lb.setText("Password");

        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        sign_up_btn.setText("Sign Up");
        sign_up_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_up_btnActionPerformed(evt);
            }
        });

        correct_lb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        correct_lb.setForeground(new java.awt.Color(204, 0, 0));

        admin_login_btn.setText("Admin Login");
        admin_login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_login_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(login_logo_lb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correct_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(user_name_tf)
                                    .addComponent(password_pf, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                            .addComponent(password_lb)
                            .addComponent(user_name_lb)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(sign_up_btn)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(admin_login_btn)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(login_logo_lb)
                .addGap(28, 28, 28)
                .addComponent(admin_login_btn)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_name_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_lb)
                    .addComponent(password_pf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_btn)
                    .addComponent(sign_up_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(correct_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
               String s1= user_name_tf.getText().trim();
               String s2 = password_pf.getText().trim();
                // where id="+s1+" and password="+s2+"
       
        try{ 
                                  
    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
    Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Wedding_planner;integratedSecurity=true");  
   
     Statement statement = connection.createStatement();  
               
 ResultSet resultSet = statement.executeQuery(" select User_name, Password from users where User_name='"+s1+"' and Password='"+s2+"' ");  
            
 
  if(resultSet.next()){
                
           new Home().setVisible(true);
                this.setVisible(false);
            }
  else{
         correct_lb.setText("User Name and password is not matched");
         user_name_tf.setText("");
         password_pf.setText("");
  }
         } catch (Exception e) {  
             e.printStackTrace();  
         }  
        
    }//GEN-LAST:event_login_btnActionPerformed

    private void sign_up_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_up_btnActionPerformed
        // TODO add your handling code here:
                new User_Registration().setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_sign_up_btnActionPerformed

    private void admin_login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_login_btnActionPerformed
        // TODO add your handling code here:
        new Admin_Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admin_login_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_login_btn;
    private javax.swing.JLabel correct_lb;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel login_logo_lb;
    private javax.swing.JLabel password_lb;
    private javax.swing.JPasswordField password_pf;
    private javax.swing.JButton sign_up_btn;
    private javax.swing.JLabel user_name_lb;
    private javax.swing.JTextField user_name_tf;
    // End of variables declaration//GEN-END:variables
}
